### ISSUE TITLE
Segfaults @ line 160 

### ISSUE THREAD

**Issue by NateZimmer** [homewsn/whsniff#7]
Been struggling with segfaults on line 160: https://github.com/homewsn/whsniff/blob/master/src/whsniff.c#L160 

```c
fwrite(&buf[sizeof(usb_data_header_type)], 1, usb_data_header->wpan_len - 2, stdout);
```
Occasionally a packet will be received where  `usb_data_header->wpan_len` is equal to 1. This results in attempting to write -1 in length to `fwrite`. Have had this issue on multiple linux distros with multiple dongles. Took awhile to find this because oddly enough when I GDB debug + attach, this never happens so I had to figure it out from a core dump. 

Presumably you have the `-2` because there are suppose to be 2 bytes appended? Kinda tricky to debug this since TI doesn't provide the sniffer firmware? Also if its just a continuous data stream, how does one recover from this? There aren't really any sync bytes?

**Comment by homewsn** [comment]
I have not come across a description of the USB sniffer protocol in open sources from TI, so everything that is implemented in this program is based on studies of USB traffic both by me and other people, and our assumptions with varying degrees of probability. Therefore, I have no idea why this happens, and whether it is caused by an error in the program, in the sniffer firmware, or something else.
Presumably, the `usb_data_header->wpan_len` byte contains the length of the WPAN packet without FCS (2 bytes), but including two more additional information bytes from the sniffer itself. Therefore the value of `usb_data_header->wpan_len` should be at least 5.
All I can offer you now is to ignore USB packets with `usb_data_header->wpan_len` less than 5 bytes. To do this, you can add the following code on line 134 https://github.com/homewsn/whsniff/blob/master/src/whsniff.c#L134:
```
if (usb_data_header->wpan_len < 5)
{
	break;
}
```

**Comment by NateZimmer** [comment]
@homewsn many thanks, that seemed to fix it! Ran overnight without segfaulting.

**Comment by kissste** [comment]
thank you, had a same issue, patched as suggested and works well.
