### ISSUE TITLE
timestamp seems wrong

### ISSUE THREAD

**Issue by badzz** [homewsn/whsniff#9]
Hi,
Great project.
I do capturing for hours to catch an issue with your tool
When I read the pcap in wireshark the timestamp are going back and forth and seems not correct as it shows 4 hours of recording after 24h of actual recordings.
![image](https://user-images.githubusercontent.com/6543969/94971651-ca303900-0507-11eb-9ed6-5f0a599187f9.png)
![image](https://user-images.githubusercontent.com/6543969/94971681-dcaa7280-0507-11eb-9492-27e3ea386d20.png)
I can send you a sample privately if it helps
Thx

**Comment by homewsn** [comment]
Thanks for the info.
I have never used a sniffer for so many hours in a row, and I have no idea yet why the timestamp is corrupting. An example pcap file is very welcome. If you want privacy, you can send the download link to my email address.

**Comment by NateZimmer** [comment]
I encountered an issue where occasionally the USB device would not get the messages designed to increment the clock. 

As an alternative method, i'd look for a roll-over in the timestamps and once I detected the rollover, i'd increment the offset. See here: https://github.com/NateZimmer/whsniff/commit/87ef92530b0adbe29c11613cbf00d5bb9e447fcd 

This method isn't exactly foolproof because if one went more than 2*(2^32/1e6) seconds without receiving a message, you could go multiple roll-over cycles. If my math is right, the rollover happens every 1.2 hours. In the case of my sniffing environments, the likelihood of not getting a packet for an entire hour is extremely small so this is the best solution for my system to be able to sniff for a long duration without issues.

**Comment by homewsn** [comment]
@NateZimmer Thank you. It seems that you are right.
I would like to suggest using your method to anyone experiencing similar problems.

**Comment by badzz** [comment]
thanks a lot
I am trying this now

**Comment by badzz** [comment]
it works for me thanks @NateZimmer 
thanks @homewsn  for this nice project
